### ISSUE TITLE
Is the param PUBLIC_URL necessary in the .env file?

### ISSUE THREAD

**Issue by jimkev** [fofr/waveformer#34]
Hi friend there, 
I have a question to consult, when it runed 'npm run dev', the REPLICATE_API_TOKEN just worked fine, but I got a error report in page 'http://localhost:3000/music/xxx' like this:
![image](https://github.com/fofr/waveformer/assets/7113888/fe85b675-3b85-4aa3-b7b7-a0dfe6cc27a1)

It looks like an error I missout the PUBLIC_URL param. shold I set a default value to PUBLIC_URL?

looking forward to your response, thanks a lot!

**Comment by jimkev** [comment]
It solved.

cause method **fetch** need a **absolute request address**. like this:
![image](https://github.com/fofr/waveformer/assets/7113888/66442faa-63dd-48d8-a86a-215ad5f580a6)

**Comment by SpacebotV-7** [comment]
can concur -  matching the above in the [id].js (found in waveformer>pages>music) file got it working on my end.

much appreciated @jimkev!
